import type { Metadata } from "next";
import { Geist, Poppins, JetBrains_Mono, Geist_Mono, } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import { Inter, Plus_Jakarta_Sans, Roboto } from "next/font/google";
import TopLoader from "./components/layout/TopLoader";
import GoogleAuthUI from "./components/layout/Contact";
import Footer from "./components/layout/Footer";


const jakarta = Roboto({
  subsets: ["latin"],
  variable: "--font-jakarta",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const JetBrains_Mono_font = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
}
);

const Inter_font = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
}
);


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${JetBrains_Mono_font.variable} ${Inter_font.variable} ${jakarta.variable} antialiased`}
      >
        <TopLoader />
        <Navbar />
        {children}
        <GoogleAuthUI/>
        <Footer/>
      </body>
    </html>
  );
}
